### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yangyid** [dbzhang800/QtXlsxWriter#193] opened 2020-02-17 08:24 UTC
F:\test\qtxlxs\QtXlsxWriter-master\QtXlsxWriter-master\src\xlsx\xlsxzipreader.cpp: In member function 'void QXlsx::ZipReader::init()':
F:\test\qtxlxs\QtXlsxWriter-master\QtXlsxWriter-master\src\xlsx\xlsxzipreader.cpp:51:66: error: conversion from 'QVector<QZipReader::FileInfo>' to non-scalar type 'QList<QZipReader::FileInfo>' requested
     QList<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();
                                            ~~~~~~~~~~~~~~~~~~~~~~^~
mingw32-make[3]: *** [Makefile.Release:2032: .obj/release/xlsxzipreader.o] Error 1

**Comment by VSRonin** [comment] 2020-02-20 12:09
Duplicate of #125

**Comment by dbzhang800** [comment] 2020-03-18 17:37
Fixed

**Closed by dbzhang800** 2020-03-18 17:37 UTC
