### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by HaodaGitHub** [dbzhang800/QtXlsxWriter#165] opened 2017-10-26 09:05 UTC
this error:
QtXlsxWriter\trunk\src\xlsx\xlsxzipreader.cpp:51: error: invalid use of incomplete type 'class QVector<QZipReader::FileInfo>'
     QList<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();
                                                                   ^

**Comment by VSRonin** [comment] 2017-10-30 08:03
Duplicate of #125

**Comment by HaodaGitHub** [comment] 2017-10-30 09:23
Has been resolved

add the head #include <QVector> in xlsxzipreader.cpp AND QList -> QVector   

rebuild   

must qmake    make

**Closed** 2020-03-18 17:38 UTC
